<div class="card">
    <div class="card-header">
        <h3 class="card-title"><i class="fas fa-list"></i> Cadastro de cursos</h3>
    </div>

    <div class="card-body p-0">


        <?php require_once __DIR__ . '/cursoForm.phtml'; ?>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Curso</th>
                    <th>Carga horária</th>
                    <th style="width: 40px">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($cursos)) : ?>

                    <tr>
                        <td colspan="4" class="text-center">Nenhum curso cadastrado</td>
                    </tr>
                <?php else: ?>

                    <?php foreach ($cursos as $curso) : ?>
                        <tr>
                            <td><?= $curso->id ?></td>
                            <td><?= $curso->nome ?></td>
                            <td><?= $curso->carga_horaria ?></td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-info btn-sm" title="Visualizar materiais do curso" onclick="detalheCurso(<?= $curso->id ?>)">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                    <button type="button" class="btn btn-warning btn-sm" title="Editar dados do curso" onclick="editarCurso(<?= $curso->id ?>)">
                                        <i class="fas fa-pencil-alt"></i>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-sm" title="Excluir curso" onclick="excluirCurso(<?= $curso->id ?>)">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
            </tbody>

        <?php endif; ?>

        <tfoot>
            <tr>
                <th colspan="4">

                    <i class="fas fa-number"></i> Registros: <?= count($cursos) ?>

                </th>
            </tr>
        </tfoot>

        </table>

    </div>

</div>