<!-- formulário para administração do cadastro do curso -->

<form action="" method="" role="form" class="container gap-1 my-2 py-2">
    <div class="form-group">
        <label for="id">ID</label>
        <input type="text" name="id" id="id" class="form-control">
    </div>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" name="nome" id="nome" class="form-control">
    </div>
    <div class="form-group">
        <label for="carga_horaria">Carga horária</label>
        <input type="text" name="carga_horaria" id="carga_horaria" class="form-control">
    </div>
    <div class="well well-sm py-2 my-2 bg-white">
        <button class="btn btn-primary btn-sm'><i class='fa fa-file"></i> Novo</button>
        <button class="btn btn-danger btn-sm'><i class='fa fa-save"></i> Salvar</button>
    </div>

</form>