<div class="card">
    <div class="card-header">
        <h3 class="card-title"><i class="fas fa-list"></i> Cadastro de cursos</h3>
    </div>

    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Curso</th>
                    <th>Carga horária</th>
                    <th style="width: 40px">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($cursos)) : ?>

                    <tr>
                        <td colspan="4" class="text-center">Nenhum curso cadastrado</td>
                    </tr>
                <?php else: ?>

                <?php foreach ($cursos as $curso) : ?>
                    <tr>
                        <td><?= $curso->id ?></td>
                        <td><?= $curso->nome ?></td>
                        <td><?= $curso->carga_horaria ?></td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-info btn-sm" onclick="editarCurso(<?= $curso->id ?>)">
                                    <i class="fas fa-pencil-alt"></i>
                                </button>
                                <button type="button" class="btn btn-danger btn-sm" onclick="excluirCurso(<?= $curso->id ?>)">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

            <?php endif; ?>

        </table>

    </div>

</div>