<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos</title>
    <link rel="stylesheet" href="vendor/twitter/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="vendor/fortawesome/font-awesome/css/all.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    
    <header>
        <div class="d-flex flex-column align-items-start topo-header">
            <div class="logo">
                <div class="topo-header-text">Descrição/Identificação</div>
            </div>
            <small>Slogan</small>
        </div>
    </header>
    <?php require_once __DIR__  .'/navbar.phtml'; ?>
    <main class="container">
                
        
    
