

<!-- Banner -->
<div class="d-flex banner-home bg-banner-home text-white text-center justify-content-center align-items-center">    
    <div class="text-banner-home">
        <h1 class="text-center text-white">Bem-vindo ao nosso site</h1>
        <h2 class="text-center text-white">Aqui você insere um texto bem legal</h2>
    </div>
    
</div>


<div class="well well-lg boxes">

   <div class="card card-body shadow justify-content-center align-items-center box">
         [destaques]
   </div>


   <div class="d-flex card card-body shadow justify-content-center align-items-center box">
        [destaques]
   </div>


   <div class="card card-body shadow justify-content-center align-items-center box">
   [destaques]
   </div>

</div>